// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9VVoTRjnly7kymqzc-_yJpSB-NoOvIHw',
    appId: '1:346229966341:web:13c3e44cdc384b548b3e6c',
    messagingSenderId: '346229966341',
    projectId: 'merzol',
    authDomain: 'merzol.firebaseapp.com',
    storageBucket: 'merzol.appspot.com',
    measurementId: 'G-39RVG0BCBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYDEz2sCq_OqFvi5_O53YmAgcSQHunI2g',
    appId: '1:346229966341:android:fab1d2182db2b5768b3e6c',
    messagingSenderId: '346229966341',
    projectId: 'merzol',
    storageBucket: 'merzol.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC15zYAzkbtDUlPA_Z5ArggWYG_TaqleaA',
    appId: '1:346229966341:ios:a3e27fc4e531920c8b3e6c',
    messagingSenderId: '346229966341',
    projectId: 'merzol',
    storageBucket: 'merzol.appspot.com',
    androidClientId: '346229966341-lrc78irm71hkjl5mb64064ulvs3n0d0i.apps.googleusercontent.com',
    iosClientId: '346229966341-jd3g8sd12o1sdon5bu938lvjeqm1au2f.apps.googleusercontent.com',
    iosBundleId: 'com.merzol.app',
  );
}
